"""Add jsonb odds columns

Revision ID: 0a78ee362485
Revises: b0918a42528c
Create Date: 2023-08-02 00:39:45.347354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a78ee362485'
down_revision = 'b0918a42528c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bet', sa.Column('handicaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_bet_total_over25', table_name='bet')
    op.drop_index('ix_bet_total_under25', table_name='bet')
    op.create_index('idx_gin_handicaps', 'bet', ['handicaps'], unique=False, postgresql_using='gin')
    op.create_index('idx_gin_totals', 'bet', ['totals'], unique=False, postgresql_using='gin')
    op.drop_column('bet', 'total_under25')
    op.drop_column('bet', 'total_over25')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('total_over25', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=True))
    op.add_column('bet', sa.Column('total_under25', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=True))
    op.drop_index('idx_gin_totals', table_name='bet', postgresql_using='gin')
    op.drop_index('idx_gin_handicaps', table_name='bet', postgresql_using='gin')
    op.create_index('ix_bet_total_under25', 'bet', ['total_under25'], unique=False)
    op.create_index('ix_bet_total_over25', 'bet', ['total_over25'], unique=False)
    op.drop_column('bet', 'handicaps')
    op.drop_column('bet', 'totals')
    # ### end Alembic commands ###
