"""Add additional outcome column

Revision ID: 243acb21cc72
Revises: a77e2357df31
Create Date: 2023-09-10 13:57:53.632038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '243acb21cc72'
down_revision = 'a77e2357df31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('second_half_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bet', sa.Column('first_half_totals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bet', sa.Column('first_half_handicaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_gin_first_half_handicaps', 'bet', ['first_half_handicaps'], unique=False, postgresql_using='gin')
    op.create_index('idx_gin_first_half_totals', 'bet', ['first_half_totals'], unique=False, postgresql_using='gin')
    op.create_index('idx_gin_second_half_outcomes', 'bet', ['second_half_outcomes'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gin_second_half_outcomes', table_name='bet', postgresql_using='gin')
    op.drop_index('idx_gin_first_half_totals', table_name='bet', postgresql_using='gin')
    op.drop_index('idx_gin_first_half_handicaps', table_name='bet', postgresql_using='gin')
    op.drop_column('bet', 'first_half_handicaps')
    op.drop_column('bet', 'first_half_totals')
    op.drop_column('bet', 'second_half_outcomes')
    # ### end Alembic commands ###
