"""Add country column to league

Revision ID: a77e2357df31
Revises: eceb33add5b9
Create Date: 2023-08-15 00:13:54.983405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77e2357df31'
down_revision = 'eceb33add5b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('country', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league', 'country')
    # ### end Alembic commands ###
