"""init

Revision ID: ab67a86ccd33
Revises: 
Create Date: 2023-04-01 18:00:47.550813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab67a86ccd33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmaker_created_at'), 'bookmaker', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookmaker_name'), 'bookmaker', ['name'], unique=False)
    op.create_index(op.f('ix_bookmaker_source_id'), 'bookmaker', ['source_id'], unique=False)
    op.create_index(op.f('ix_bookmaker_updated_at'), 'bookmaker', ['updated_at'], unique=False)
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('flag', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_created_at'), 'country', ['created_at'], unique=False)
    op.create_index(op.f('ix_country_updated_at'), 'country', ['updated_at'], unique=False)
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_created_at'), 'league', ['created_at'], unique=False)
    op.create_index(op.f('ix_league_source_id'), 'league', ['source_id'], unique=False)
    op.create_index(op.f('ix_league_updated_at'), 'league', ['updated_at'], unique=False)
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('odds_coverage', sa.Boolean(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_created_at'), 'season', ['created_at'], unique=False)
    op.create_index(op.f('ix_season_current'), 'season', ['current'], unique=False)
    op.create_index(op.f('ix_season_end'), 'season', ['end'], unique=False)
    op.create_index(op.f('ix_season_league_id'), 'season', ['league_id'], unique=False)
    op.create_index(op.f('ix_season_odds_coverage'), 'season', ['odds_coverage'], unique=False)
    op.create_index(op.f('ix_season_start'), 'season', ['start'], unique=False)
    op.create_index(op.f('ix_season_updated_at'), 'season', ['updated_at'], unique=False)
    op.create_index(op.f('ix_season_year'), 'season', ['year'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('founded_at', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('national', sa.Boolean(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_country_id'), 'team', ['country_id'], unique=False)
    op.create_index(op.f('ix_team_created_at'), 'team', ['created_at'], unique=False)
    op.create_index(op.f('ix_team_founded_at'), 'team', ['founded_at'], unique=False)
    op.create_index(op.f('ix_team_source_id'), 'team', ['source_id'], unique=False)
    op.create_index(op.f('ix_team_updated_at'), 'team', ['updated_at'], unique=False)
    op.create_table('fixture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('league_season', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('away_team_logo', sa.String(length=255), nullable=False),
    sa.Column('away_team_source_id', sa.Integer(), nullable=False),
    sa.Column('away_team_name', sa.String(length=255), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team_logo', sa.String(length=255), nullable=False),
    sa.Column('home_team_source_id', sa.Integer(), nullable=False),
    sa.Column('home_team_name', sa.String(length=255), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_away_team_id'), 'fixture', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_fixture_away_team_name'), 'fixture', ['away_team_name'], unique=False)
    op.create_index(op.f('ix_fixture_away_team_source_id'), 'fixture', ['away_team_source_id'], unique=False)
    op.create_index(op.f('ix_fixture_created_at'), 'fixture', ['created_at'], unique=False)
    op.create_index(op.f('ix_fixture_date'), 'fixture', ['date'], unique=False)
    op.create_index(op.f('ix_fixture_home_team_id'), 'fixture', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_fixture_home_team_name'), 'fixture', ['home_team_name'], unique=False)
    op.create_index(op.f('ix_fixture_home_team_source_id'), 'fixture', ['home_team_source_id'], unique=False)
    op.create_index(op.f('ix_fixture_league_id'), 'fixture', ['league_id'], unique=False)
    op.create_index(op.f('ix_fixture_source_id'), 'fixture', ['source_id'], unique=False)
    op.create_index(op.f('ix_fixture_source_update'), 'fixture', ['source_update'], unique=False)
    op.create_index(op.f('ix_fixture_updated_at'), 'fixture', ['updated_at'], unique=False)
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bookmaker', sa.String(length=255), nullable=False),
    sa.Column('home_win', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('away_win', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('draw', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('total_under25', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('total_over25', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_away_win'), 'bet', ['away_win'], unique=False)
    op.create_index(op.f('ix_bet_bookmaker'), 'bet', ['bookmaker'], unique=False)
    op.create_index(op.f('ix_bet_created_at'), 'bet', ['created_at'], unique=False)
    op.create_index(op.f('ix_bet_draw'), 'bet', ['draw'], unique=False)
    op.create_index(op.f('ix_bet_fixture_id'), 'bet', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_bet_home_win'), 'bet', ['home_win'], unique=False)
    op.create_index(op.f('ix_bet_source'), 'bet', ['source'], unique=False)
    op.create_index(op.f('ix_bet_source_id'), 'bet', ['source_id'], unique=False)
    op.create_index(op.f('ix_bet_source_update'), 'bet', ['source_update'], unique=False)
    op.create_index(op.f('ix_bet_total_over25'), 'bet', ['total_over25'], unique=False)
    op.create_index(op.f('ix_bet_total_under25'), 'bet', ['total_under25'], unique=False)
    op.create_index(op.f('ix_bet_updated_at'), 'bet', ['updated_at'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_fixture_id'), 'notification', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_notification_sent_at'), 'notification', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notification_updated_at'), 'notification', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_updated_at'), table_name='notification')
    op.drop_index(op.f('ix_notification_sent_at'), table_name='notification')
    op.drop_index(op.f('ix_notification_fixture_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_bet_updated_at'), table_name='bet')
    op.drop_index(op.f('ix_bet_total_under25'), table_name='bet')
    op.drop_index(op.f('ix_bet_total_over25'), table_name='bet')
    op.drop_index(op.f('ix_bet_source_update'), table_name='bet')
    op.drop_index(op.f('ix_bet_source_id'), table_name='bet')
    op.drop_index(op.f('ix_bet_source'), table_name='bet')
    op.drop_index(op.f('ix_bet_home_win'), table_name='bet')
    op.drop_index(op.f('ix_bet_fixture_id'), table_name='bet')
    op.drop_index(op.f('ix_bet_draw'), table_name='bet')
    op.drop_index(op.f('ix_bet_created_at'), table_name='bet')
    op.drop_index(op.f('ix_bet_bookmaker'), table_name='bet')
    op.drop_index(op.f('ix_bet_away_win'), table_name='bet')
    op.drop_table('bet')
    op.drop_index(op.f('ix_fixture_updated_at'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_source_update'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_source_id'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_league_id'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_home_team_source_id'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_home_team_name'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_home_team_id'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_date'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_created_at'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_away_team_source_id'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_away_team_name'), table_name='fixture')
    op.drop_index(op.f('ix_fixture_away_team_id'), table_name='fixture')
    op.drop_table('fixture')
    op.drop_index(op.f('ix_team_updated_at'), table_name='team')
    op.drop_index(op.f('ix_team_source_id'), table_name='team')
    op.drop_index(op.f('ix_team_founded_at'), table_name='team')
    op.drop_index(op.f('ix_team_created_at'), table_name='team')
    op.drop_index(op.f('ix_team_country_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_season_year'), table_name='season')
    op.drop_index(op.f('ix_season_updated_at'), table_name='season')
    op.drop_index(op.f('ix_season_start'), table_name='season')
    op.drop_index(op.f('ix_season_odds_coverage'), table_name='season')
    op.drop_index(op.f('ix_season_league_id'), table_name='season')
    op.drop_index(op.f('ix_season_end'), table_name='season')
    op.drop_index(op.f('ix_season_current'), table_name='season')
    op.drop_index(op.f('ix_season_created_at'), table_name='season')
    op.drop_table('season')
    op.drop_index(op.f('ix_league_updated_at'), table_name='league')
    op.drop_index(op.f('ix_league_source_id'), table_name='league')
    op.drop_index(op.f('ix_league_created_at'), table_name='league')
    op.drop_table('league')
    op.drop_index(op.f('ix_country_updated_at'), table_name='country')
    op.drop_index(op.f('ix_country_created_at'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_bookmaker_updated_at'), table_name='bookmaker')
    op.drop_index(op.f('ix_bookmaker_source_id'), table_name='bookmaker')
    op.drop_index(op.f('ix_bookmaker_name'), table_name='bookmaker')
    op.drop_index(op.f('ix_bookmaker_created_at'), table_name='bookmaker')
    op.drop_table('bookmaker')
    # ### end Alembic commands ###
