"""add event_url field to bet

Revision ID: b0918a42528c
Revises: c90b5433b984
Create Date: 2023-05-16 20:32:03.983784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0918a42528c'
down_revision = 'c90b5433b984'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('event_url', sa.String(length=511), nullable=True))
    op.create_index(op.f('ix_bet_event_url'), 'bet', ['event_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_event_url'), table_name='bet')
    op.drop_column('bet', 'event_url')
    # ### end Alembic commands ###
