"""set source_id in bet to nullable

Revision ID: bb47f8eab4d4
Revises: 6edae228189e
Create Date: 2023-04-02 03:49:26.001013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb47f8eab4d4'
down_revision = '6edae228189e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bet', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bet', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
