"""make bet odds nullable

Revision ID: c90b5433b984
Revises: bb47f8eab4d4
Create Date: 2023-04-02 03:51:24.148918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90b5433b984'
down_revision = 'bb47f8eab4d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bet', 'home_win',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=True)
    op.alter_column('bet', 'away_win',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=True)
    op.alter_column('bet', 'draw',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=True)
    op.alter_column('bet', 'total_under25',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=True)
    op.alter_column('bet', 'total_over25',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bet', 'total_over25',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=False)
    op.alter_column('bet', 'total_under25',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=False)
    op.alter_column('bet', 'draw',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=False)
    op.alter_column('bet', 'away_win',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=False)
    op.alter_column('bet', 'home_win',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=False)
    # ### end Alembic commands ###
