"""Add outcomes jsonb columns

Revision ID: eceb33add5b9
Revises: 0a78ee362485
Create Date: 2023-08-02 15:15:01.479394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eceb33add5b9'
down_revision = '0a78ee362485'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bet', sa.Column('first_half_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_gin_first_half_outcomes', 'bet', ['first_half_outcomes'], unique=False, postgresql_using='gin')
    op.create_index('idx_gin_outcomes', 'bet', ['outcomes'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gin_outcomes', table_name='bet', postgresql_using='gin')
    op.drop_index('idx_gin_first_half_outcomes', table_name='bet', postgresql_using='gin')
    op.drop_column('bet', 'first_half_outcomes')
    op.drop_column('bet', 'outcomes')
    # ### end Alembic commands ###
