from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE "bet" ALTER COLUMN "total_under25" TYPE DECIMAL(12,6) USING "total_under25"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "total_under25" TYPE DECIMAL(12,6) USING "total_under25"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "total_under25" TYPE DECIMAL(12,6) USING "total_under25"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "total_under25" TYPE DECIMAL(12,6) USING "total_under25"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "total_under25" TYPE DECIMAL(12,6) USING "total_under25"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "home_win" TYPE DECIMAL(12,6) USING "home_win"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "home_win" TYPE DECIMAL(12,6) USING "home_win"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "home_win" TYPE DECIMAL(12,6) USING "home_win"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "home_win" TYPE DECIMAL(12,6) USING "home_win"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "home_win" TYPE DECIMAL(12,6) USING "home_win"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "total_over25" TYPE DECIMAL(12,6) USING "total_over25"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "total_over25" TYPE DECIMAL(12,6) USING "total_over25"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "total_over25" TYPE DECIMAL(12,6) USING "total_over25"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "total_over25" TYPE DECIMAL(12,6) USING "total_over25"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "total_over25" TYPE DECIMAL(12,6) USING "total_over25"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "away_win" TYPE DECIMAL(12,6) USING "away_win"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "away_win" TYPE DECIMAL(12,6) USING "away_win"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "away_win" TYPE DECIMAL(12,6) USING "away_win"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "away_win" TYPE DECIMAL(12,6) USING "away_win"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "away_win" TYPE DECIMAL(12,6) USING "away_win"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "draw" TYPE DECIMAL(12,6) USING "draw"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "draw" TYPE DECIMAL(12,6) USING "draw"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "draw" TYPE DECIMAL(12,6) USING "draw"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "draw" TYPE DECIMAL(12,6) USING "draw"::DECIMAL(12,6);
        ALTER TABLE "bet" ALTER COLUMN "draw" TYPE DECIMAL(12,6) USING "draw"::DECIMAL(12,6);"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE "bet" ALTER COLUMN "total_under25" TYPE DOUBLE PRECISION USING "total_under25"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "total_under25" TYPE DOUBLE PRECISION USING "total_under25"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "total_under25" TYPE DOUBLE PRECISION USING "total_under25"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "total_under25" TYPE DOUBLE PRECISION USING "total_under25"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "home_win" TYPE DOUBLE PRECISION USING "home_win"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "home_win" TYPE DOUBLE PRECISION USING "home_win"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "home_win" TYPE DOUBLE PRECISION USING "home_win"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "home_win" TYPE DOUBLE PRECISION USING "home_win"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "total_over25" TYPE DOUBLE PRECISION USING "total_over25"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "total_over25" TYPE DOUBLE PRECISION USING "total_over25"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "total_over25" TYPE DOUBLE PRECISION USING "total_over25"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "total_over25" TYPE DOUBLE PRECISION USING "total_over25"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "away_win" TYPE DOUBLE PRECISION USING "away_win"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "away_win" TYPE DOUBLE PRECISION USING "away_win"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "away_win" TYPE DOUBLE PRECISION USING "away_win"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "away_win" TYPE DOUBLE PRECISION USING "away_win"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "draw" TYPE DOUBLE PRECISION USING "draw"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "draw" TYPE DOUBLE PRECISION USING "draw"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "draw" TYPE DOUBLE PRECISION USING "draw"::DOUBLE PRECISION;
        ALTER TABLE "bet" ALTER COLUMN "draw" TYPE DOUBLE PRECISION USING "draw"::DOUBLE PRECISION;"""
